Import-Module $PSScriptRoot\vasp2Visual.psm1
Import-Module $PSScriptRoot\Automation.psm1 
Import-Module $PSScriptRoot\MakeSlab.psm1
Import-Module $PSScriptRoot\PlotlyInteractive.psm1
Import-Module $PSScriptRoot\Alignment.psm1
Import-Module $PSScriptRoot\Beamer.psm1
Import-Module $PSScriptRoot\DOS.psm1
Import-Module $PSScriptRoot\Version2\ExtractXml.psm1
Import-Module $PSScriptRoot\Version2\GeneralFunctions.psm1