# Module manifest for module 'GetProjections'
# Generated by: Abdul Saboor
# Created: 2019-14-09
@{
    RootModule='RootModule.psm1'
    # Version number of this module.
    ModuleVersion = '1.0.2.1'   
    # Author of this module
    Author = 'Abdul Saboor'
    GUID = 'e6228475-2920-41ae-be19-934548eb19ce'
    CompanyName = 'Self Created during PhD in University of Delaware USA.'
    Copyright = '(c) 2019 Abdul Saboor. All rights reserved.'
    # Description of the functionality provided by this module
    Description = 'A vasp pre/post-processing module. https://github.com/massgh/Vasp2Visual/tree/master'
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'
    
    # Minimum version of Microsoft .NET Framework required by this module
    DotNetFrameworkVersion = '4.8'
    FunctionsToExport = '*'
    CmdletsToExport = '*'
    VariablesToExport = '*'
    AliasesToExport = '*'   
    }